### PR TITLE
Initial state estimator implementation

### PR DESCRIPTION
**Pull request by coma6440**
Implements a basic KF for 3D, constant velocity motion. There is potential for an issue for predicting a time that is greater than 1 time-step away that needs to be discussed.

### CODE REVIEW

**Comment by aacorn** [comment]
> Implements a basic KF for 3D, constant velocity motion. There is potential for an issue for predicting a time that is greater than 1 time-step away that needs to be discussed.

What is the potential issue?

**Comment by coma6440** [comment]
The current structure requests a time for the estimator, but currently it can only predict 1 time-step ahead. Additionally, that timestep might not line up with the requested time

**Comment by aacorn** [comment]
It looks like the filter only takes an explicit timestep representation when we're using one of the standard motion models, when we get a full custom model in the timestep will be implicit in the motion model. In the mean time we can specify a 'number of steps' parameter and divide the total time difference by that parameter to get the timestep size, then loop the filter recursively until we've reached the appropriate time, I imagine we'd like to do this with a copy of the filter so we can desync the actual filter steps from the filter's prediction at collision time.

**Comment by coma6440** [comment]
A solution to this that I think may be more computationally efficient is to define the step size of the next iteration based on a current estimator time and the requested time. This requires only one prediction step.

**Pull request merged**
